version: '3'

includes:
  assets: ./pipeline/scripts/Taskfile.yml

tasks:
  deps:system:
    desc: Install system dependencies (Blender, Python3-NumPy)
    cmds:
      - task: deps:system:linux
      - task: deps:system:darwin

  deps:system:linux:
    internal: true
    platforms: [linux]
    cmds:
      - echo "Installing system dependencies (Linux)..."
      - sudo apt-get update && sudo apt-get install -y blender python3-numpy
    status:
      - which blender
      - dpkg -s python3-numpy

  deps:system:darwin:
    internal: true
    platforms: [darwin]
    cmds:
      - echo "Installing system dependencies (macOS)..."
      - brew install --cask blender
    status:
      - test -d /Applications/Blender.app

  build:assets:
    desc: Build DAMP assets (GLB, Textures, Catalog)
    deps: [deps:system]
    cmds:
      - task: assets:build

  build:dist:
    desc: Build the production distribution
    deps: [build:assets]
    cmds:
      - rm -rf dist
      - mkdir -p dist/tools
      - cp index.html dist/
      - cp style.css dist/
      - cp -r src dist/
      - cp -r tools/viewer dist/tools/
      - cp VERSION dist/
      - cp -r assets dist/
      - touch dist/.nojekyll
      # Timestamp injection (Cross-platform compatible)
      - sh -c "sed -i.bak \"s/<!--TIMESTAMP-->/$(date -u '+%Y-%m-%d %H:%M')/g\" dist/index.html && rm dist/index.html.bak"

  dev:
    desc: Start the main game server
    deps: [build:assets]
    cmds:
      - bun x http-server -p 3000 -c-1 -o /index.html

  dev:bg:
    desc: Start the main game server in the background using a helper script (Port 3030)
    deps: [build:assets]
    cmds:
      - ./scripts/start_server.sh 3030
      - echo "Waiting for server to start..."
      - sleep 2
      - curl -f -s http://127.0.0.1:3030/index.html > /dev/null && echo "Server is up!" || (echo "Server failed to start"; cat server.log; exit 1)

  dev:stop:
    desc: Stop the background game server
    cmds:
      - sh -c "if [ -f server.pid ]; then kill $(cat server.pid) 2>/dev/null || true; rm server.pid; echo 'Server stopped via PID'; else echo 'No server.pid found'; fi"
      - pkill -f "http-server -p 3030" || true
      - rm -f server.log
      - echo "Cleanup complete"
    ignore_error: true

  test:smoke:
    desc: Verify the game server is running and serving files
    cmds:
      - curl -f -s http://127.0.0.1:3030/index.html > /dev/null && echo "✅ Index reachable"
      - curl -f -s http://127.0.0.1:3030/src/core/game.js > /dev/null && echo "✅ Core JS reachable"
      - echo "Smoke test passed!"

  damp:viewer:
    desc: Start the DAMP asset viewer server
    deps: [build:assets]
    cmds:
      - bun x http-server -p 8080 -c-1 -o /tools/viewer/index.html

  docs:serve:
    desc: Serve documentation using mkdocs
    cmds:
      - echo "Starting mkdocs server on http://localhost:8000"
      - uvx --with mkdocs-material --with pymdown-extensions mkdocs serve
