version: '3'

includes:
  assets: ./pipeline/scripts/Taskfile.yml

tasks:
  deps:system:
    desc: Install system dependencies (Blender, Python3-NumPy)
    cmds:
      - task: deps:system:linux
      - task: deps:system:darwin

  deps:system:linux:
    internal: true
    platforms: [linux]
    cmds:
      - echo "Installing system dependencies (Linux)..."
      - sudo apt-get update && sudo apt-get install -y blender python3-numpy
    status:
      - which blender
      - dpkg -s python3-numpy

  deps:system:darwin:
    internal: true
    platforms: [darwin]
    cmds:
      - echo "Installing system dependencies (macOS)..."
      - brew install --cask blender
    status:
      - test -d /Applications/Blender.app

  deps:docs:
    desc: Install documentation dependencies
    cmds:
      - pip install mkdocs mkdocs-material mdformat mdformat-gfm mdformat-frontmatter mdformat-mkdocs

  docs:build:
    desc: Build documentation site
    deps: [deps:docs]
    cmds:
      - mkdocs build -d dist/docs

  docs:format:
    desc: Format documentation
    deps: [deps:docs]
    cmds:
      - mdformat docs/ README.md GEMINI.md

  build:assets:
    desc: Build DAMP assets (GLB, Textures, Catalog)
    deps: [deps:system]
    cmds:
      - task: assets:build

  build:dist:
    desc: Build the production distribution
    deps: [build:assets]
    cmds:
      - rm -rf dist
      - mkdir -p dist/tools
      - cp index.html dist/
      - cp style.css dist/
      - cp -r src dist/
      - cp -r tools/viewer dist/tools/
      - cp VERSION dist/
      - cp -r assets dist/
      - touch dist/.nojekyll
      # Timestamp injection (Cross-platform compatible)
      - sh -c "sed -i.bak \"s/<!--TIMESTAMP-->/$(date -u '+%Y-%m-%d %H:%M')/g\" dist/index.html && rm dist/index.html.bak"
      # Build docs
      - task: docs:build

  dev:
    desc: Start the main game server
    deps: [build:assets]
    cmds:
      - bun x http-server -p 3000 -c-1 -o /index.html

  damp:viewer:
    desc: Start the DAMP asset viewer server
    deps: [build:assets]
    cmds:
      - bun x http-server -p 8080 -c-1 -o /tools/viewer/index.html
