version: '3'

includes:
  assets: ./scripts/Taskfile.yml

tasks:
  deps:system:
    desc: Install system dependencies (Blender, Python3-NumPy)
    cmds:
      - task: deps:system:linux
      - task: deps:system:darwin

  deps:system:linux:
    internal: true
    platforms: [linux]
    cmds:
      - echo "Installing system dependencies (Linux)..."
      - sudo apt-get update && sudo apt-get install -y blender python3-numpy
    status:
      - which blender
      - dpkg -s python3-numpy

  deps:system:darwin:
    internal: true
    platforms: [darwin]
    cmds:
      - echo "Installing system dependencies (macOS)..."
      - brew install --cask blender
    status:
      - test -d /Applications/Blender.app

  deps:node:
    desc: Install Node.js dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json

  build:assets:
    desc: Build DAMP assets (GLB, Textures, Catalog)
    deps: [deps:system]
    cmds:
      - task: assets:build

  build:dist:
    desc: Build the production distribution
    deps: [deps:node, build:assets]
    cmds:
      - rm -rf dist
      - mkdir -p dist
      - cp index.html dist/
      - cp style.css dist/
      - cp -r js dist/
      - cp -r viewer dist/
      - cp VERSION dist/
      - cp -r assets dist/
      - rm -rf dist/assets/source
      - touch dist/.nojekyll
      # Timestamp injection (Cross-platform compatible)
      - sh -c "sed -i.bak \"s/<!--TIMESTAMP-->/$(date -u '+%Y-%m-%d %H:%M')/g\" dist/index.html && rm dist/index.html.bak"

  dev:
    desc: Start the main game server
    deps: [deps:node, build:assets]
    cmds:
      - bun x http-server -p 3000 -o /index.html

  viewer:
    desc: Start the legacy asset viewer server
    deps: [deps:node, build:assets]
    cmds:
      - bun x http-server -p 8000 -o /verification/asset_viewer.html

  damp:viewer:
    desc: Start the DAMP asset viewer server
    deps: [deps:node, build:assets]
    cmds:
      - bun x http-server -p 8080 -c-1 -o /viewer/index.html
