version: '3'

tasks:
  deps:system:
    desc: Install system dependencies (Blender, Python3-NumPy)
    cmds:
      - task: deps:system:linux
      - task: deps:system:darwin

  deps:system:linux:
    internal: true
    platforms: [linux]
    cmds:
      - echo "Installing system dependencies (Linux)..."
      - sudo apt-get update && sudo apt-get install -y blender python3-numpy
    status:
      - which blender
      - dpkg -s python3-numpy

  deps:system:darwin:
    internal: true
    platforms: [darwin]
    cmds:
      - echo "Installing system dependencies (macOS)..."
      - brew install --cask blender
    status:
      - test -d /Applications/Blender.app

  deps:node:
    desc: Install Node.js dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json

  build:assets:
    desc: Build Blender assets (GLB and Textures)
    deps: [deps:system]
    cmds:
      - node scripts/build-blender-assets.js
    sources:
      - assets/source/blender/*.py
    generates:
      - assets/bulldozer_components.glb
      - assets/bulldozer_texture.png

  dev:
    desc: Start the main game server
    deps: [deps:node, build:assets]
    cmds:
      - open http://localhost:3000 || xdg-open http://localhost:3000 || echo "Open http://localhost:3000"
      - npx serve

  viewer:
    desc: Start the asset viewer server
    deps: [deps:node, build:assets]
    cmds:
      - open http://localhost:8000/verification/asset_viewer.html || xdg-open http://localhost:8000/verification/asset_viewer.html || echo "Open http://localhost:8000/verification/asset_viewer.html"
      - python3 -m http.server 8000