version: '3'

tasks:
  build:
    desc: Build assets for the viewer (Geometry + Textures)
    cmds:
      - node ../scripts/build-assets.js

  serve:
    desc: Serve the viewer locally
    cmds:
      - echo "Serving viewer on http://localhost:8080"
      - python3 -m http.server 8080
    dir: .

  dev:
    desc: Build and then serve
    deps: [build]
    cmds:
      - task: serve
